/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Program08;

/**
 *
 * @author mathe
 */
public class Times extends javax.swing.JFrame {

    /**
     * Creates new form Times
     */
    public Times() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoButton = new javax.swing.ButtonGroup();
        jRCapricornio = new javax.swing.JRadioButton();
        jRPeixes = new javax.swing.JRadioButton();
        jRSagitario = new javax.swing.JRadioButton();
        jBSair = new javax.swing.JButton();
        jBVeja = new javax.swing.JButton();
        jRAries = new javax.swing.JRadioButton();
        jRTouro = new javax.swing.JRadioButton();
        jRGemeos = new javax.swing.JRadioButton();
        jRCancer = new javax.swing.JRadioButton();
        jRLeoes = new javax.swing.JRadioButton();
        jRVirgem = new javax.swing.JRadioButton();
        jRLibra = new javax.swing.JRadioButton();
        jREscorpiao = new javax.swing.JRadioButton();
        jRAquario = new javax.swing.JRadioButton();
        jRSantos = new javax.swing.JRadioButton();
        jRVasco = new javax.swing.JRadioButton();
        jRSport = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        GrupoButton.add(jRCapricornio);
        jRCapricornio.setText("Internacional");

        GrupoButton.add(jRPeixes);
        jRPeixes.setText("Cruzeiro");

        GrupoButton.add(jRSagitario);
        jRSagitario.setText("Coritiba");

        jBSair.setText("Sair");
        jBSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSairActionPerformed(evt);
            }
        });

        jBVeja.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBVeja.setText("Veja a data de Fundação");
        jBVeja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVejaActionPerformed(evt);
            }
        });

        GrupoButton.add(jRAries);
        jRAries.setText("Atlético - MG");

        GrupoButton.add(jRTouro);
        jRTouro.setText("Atlético - PR");

        GrupoButton.add(jRGemeos);
        jRGemeos.setText("Palmeiras");

        GrupoButton.add(jRCancer);
        jRCancer.setText("Corinthians");

        GrupoButton.add(jRLeoes);
        jRLeoes.setText("São Paulo");

        GrupoButton.add(jRVirgem);
        jRVirgem.setText("Botafogo");
        jRVirgem.setToolTipText("");

        GrupoButton.add(jRLibra);
        jRLibra.setText("Fluminense");

        GrupoButton.add(jREscorpiao);
        jREscorpiao.setText("Flamengo");
        jREscorpiao.setToolTipText("");

        GrupoButton.add(jRAquario);
        jRAquario.setText("Grêmio");

        GrupoButton.add(jRSantos);
        jRSantos.setText("Santos");

        GrupoButton.add(jRVasco);
        jRVasco.setText("Vasco");
        jRVasco.setToolTipText("");

        GrupoButton.add(jRSport);
        jRSport.setText("Sport");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRAries)
                    .addComponent(jRTouro)
                    .addComponent(jRGemeos)
                    .addComponent(jRCancer)
                    .addComponent(jRSantos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRVasco)
                    .addComponent(jRLeoes)
                    .addComponent(jRVirgem)
                    .addComponent(jRLibra)
                    .addComponent(jREscorpiao))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRSagitario)
                    .addComponent(jRCapricornio)
                    .addComponent(jRAquario)
                    .addComponent(jRPeixes)
                    .addComponent(jRSport))
                .addGap(8, 8, 8))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBVeja, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBSair, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jRCapricornio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRAquario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRPeixes))
                    .addComponent(jRSagitario)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRAries)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRTouro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRGemeos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRCancer))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRLeoes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRVirgem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRLibra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jREscorpiao)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRVasco)
                    .addComponent(jRSantos)
                    .addComponent(jRSport))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBVeja, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBSair, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jBSairActionPerformed

    private void jBVejaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVejaActionPerformed
        if(jRAries.isSelected()){
            JOptionPane.showMessageDialog(null, "O primeiro signo do Zodiaco, está sempre tomando a frente das situações.");
        }
        else if(jRTouro.isSelected()){
            JOptionPane.showMessageDialog(null, "Pode ser do elemento Terra, gosta de ter o controle das situações em suas mãos.");
        }
        else if(jRGemeos.isSelected()){
            JOptionPane.showMessageDialog(null, "É inteligente, dinâmica, vibrante, sempre em busca de novos desafios.");
        }
        else if(jRCancer.isSelected()){
            JOptionPane.showMessageDialog(null, "Tem uma grande intuição, que a guia nos momentos-chave do destino..");
        }
        else if(jRLeoes.isSelected()){
            JOptionPane.showMessageDialog(null, "Tem muitos talentos, adora balada, música, cinema e ama animais de estimação.");
        }
        else if(jRVirgem.isSelected()){
            JOptionPane.showMessageDialog(null, "Tem muito talento para escrita, e têm um jeitinho crítico, que pode ajudá-las na profissão.");
        }
        else if(jRLibra.isSelected()){
            JOptionPane.showMessageDialog(null, "Você, sabe o valor das outras pessoas, das boas amizades e dos relacionamentos afetivos.");
        }
        else if(jREscorpiao.isSelected()){
            JOptionPane.showMessageDialog(null, "Sua persistência e teimosia podem ultrapassar muitas barreiras.");
        }
        else if(jRSagitario.isSelected()){
            JOptionPane.showMessageDialog(null, "Seu jeito expansivo não passa despercebido.");
        }
        else if(jRCapricornio.isSelected()){
            JOptionPane.showMessageDialog(null, "Você não foge de uma boa discussão e adora uma balada.");
        }
        else if(jRAquario.isSelected()){
            JOptionPane.showMessageDialog(null, "Seu signo é chamado de futurista.");
        }
        else if(jRPeixes.isSelected()){
            JOptionPane.showMessageDialog(null, "Tem desejo de fazer algo grandioso pelo mundo.");
        }
    }//GEN-LAST:event_jBVejaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Times.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Times.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Times.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Times.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Times().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GrupoButton;
    private javax.swing.JButton jBSair;
    private javax.swing.JButton jBVeja;
    private javax.swing.JRadioButton jRAquario;
    private javax.swing.JRadioButton jRAries;
    private javax.swing.JRadioButton jRCancer;
    private javax.swing.JRadioButton jRCapricornio;
    private javax.swing.JRadioButton jREscorpiao;
    private javax.swing.JRadioButton jRGemeos;
    private javax.swing.JRadioButton jRLeoes;
    private javax.swing.JRadioButton jRLibra;
    private javax.swing.JRadioButton jRPeixes;
    private javax.swing.JRadioButton jRSagitario;
    private javax.swing.JRadioButton jRSantos;
    private javax.swing.JRadioButton jRSport;
    private javax.swing.JRadioButton jRTouro;
    private javax.swing.JRadioButton jRVasco;
    private javax.swing.JRadioButton jRVirgem;
    // End of variables declaration//GEN-END:variables
}
