/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Program07;

/**
 *
 * @author mathe
 */
public class Escolhendo_Signo extends javax.swing.JFrame {

    /**
     * Creates new form Escolhendo_Signo
     */
    public Escolhendo_Signo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRAries = new javax.swing.JRadioButton();
        jRTouro = new javax.swing.JRadioButton();
        jRGemeos = new javax.swing.JRadioButton();
        jRCancer = new javax.swing.JRadioButton();
        jRLeoes = new javax.swing.JRadioButton();
        jRVirgem = new javax.swing.JRadioButton();
        jRLibra = new javax.swing.JRadioButton();
        jREscorpiao = new javax.swing.JRadioButton();
        jRAquario = new javax.swing.JRadioButton();
        jRCapricornio = new javax.swing.JRadioButton();
        jRPeixes = new javax.swing.JRadioButton();
        jRSagitario = new javax.swing.JRadioButton();
        jBSair = new javax.swing.JButton();
        jBVeja = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Escolha seu Signo");
        setIconImages(null);
        setResizable(false);

        jRAries.setText("Aries");

        jRTouro.setText("Touro");

        jRGemeos.setText("Gêmeos");

        jRCancer.setText("Câncer");

        jRLeoes.setText("Leões");

        jRVirgem.setText("Virgem");
        jRVirgem.setToolTipText("");

        jRLibra.setText("Libra");

        jREscorpiao.setText("Escorpião");
        jREscorpiao.setToolTipText("");

        jRAquario.setText("Aquário");

        jRCapricornio.setText("Capricórnio");

        jRPeixes.setText("Peixes");

        jRSagitario.setText("Sagitário");

        jBSair.setText("Sair");
        jBSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSairActionPerformed(evt);
            }
        });

        jBVeja.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBVeja.setText("Veja o que diz seu Signo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRAries)
                            .addComponent(jRTouro)
                            .addComponent(jRGemeos)
                            .addComponent(jRCancer))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRLeoes)
                            .addComponent(jRVirgem)
                            .addComponent(jRLibra)
                            .addComponent(jREscorpiao))
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRSagitario)
                            .addComponent(jRCapricornio)
                            .addComponent(jRAquario)
                            .addComponent(jRPeixes)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBVeja, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBSair, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jRCapricornio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRAquario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRPeixes))
                    .addComponent(jRSagitario)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRAries)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRTouro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRGemeos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRCancer))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRLeoes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRVirgem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRLibra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jREscorpiao)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBSair, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBVeja, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSairActionPerformed
      System.exit(0);
    }//GEN-LAST:event_jBSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Escolhendo_Signo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Escolhendo_Signo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Escolhendo_Signo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Escolhendo_Signo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Escolhendo_Signo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBSair;
    private javax.swing.JButton jBVeja;
    private javax.swing.JRadioButton jRAquario;
    private javax.swing.JRadioButton jRAries;
    private javax.swing.JRadioButton jRCancer;
    private javax.swing.JRadioButton jRCapricornio;
    private javax.swing.JRadioButton jREscorpiao;
    private javax.swing.JRadioButton jRGemeos;
    private javax.swing.JRadioButton jRLeoes;
    private javax.swing.JRadioButton jRLibra;
    private javax.swing.JRadioButton jRPeixes;
    private javax.swing.JRadioButton jRSagitario;
    private javax.swing.JRadioButton jRTouro;
    private javax.swing.JRadioButton jRVirgem;
    // End of variables declaration//GEN-END:variables
}
